config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :inquiries, only: [:index, :show] do
    # resource :form_submission_settings, only: [:edit, :update]
      member do
        get :complete
      end
    end
  end
  post '/inquiries' => 'inquiries#create'
  get "/apply_coupons" => "coupons#show"
  patch "/apply_coupons" => "coupons#update"
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  
  checkout_flow do
    puts "------------------------------------------------------------------do something order checkout_flow"
    go_to_state :address
    go_to_state :delivery
    go_to_state :payment, if: ->(order) {
      order.update_totals
      # order.payment_required?
    }
    go_to_state :confirm
    go_to_state :complete
  end
  
  def payment_required?
    # self.payments.each {|p| puts "\n\r -- #{p.inspect} \n\r"}
    return false
  end
  
end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do
  
  def determine_state(order)
    puts "----------------------------------------- Whats here"
    puts "----------------------------------------- #{determine_if_paid_with_credit_line(order)}"
    return 'canceled' if order.canceled?
    return 'pending' unless order.can_ship?
    return 'pending' if inventory_units.any? &:backordered?
    return 'shipped' if state == 'shipped'
     (order.paid? || determine_if_paid_with_credit_line(order)) || Spree::Config[:auto_capture_on_dispatch] ? 'ready' : 'pending'
  end
  
  def determine_if_paid_with_credit_line(order)
    return Spree::Order.find(order.id).payments.where(:payment_method_id => Spree::PaymentMethod.find_by(:type => "Spree::PaymentMethod::CreditLine", :active => true), :state => "completed").count > 0
  end
  
end

app/controllers/spree/coupons_controller.rb
module Spree 
  
  class CouponsController < Spree::StoreController
  
    def show
      render "spree/checkout/coupon_form"
    end
    
    def update
      @order = Spree::Order.find(params[:order][:order_id])
      
      if params[:order] && params[:order][:coupon_code]
        @order.coupon_code = params[:order][:coupon_code]
        handler = PromotionHandler::Coupon.new(@order).apply
        if handler.error.present?
          @order.errors.add(:base, handler.error)
          # respond_with(@order) { |format| format.js { render "spree/checkout/coupon_form" } } and return
          @result = "error"
        elsif handler.success
          flash[:success] = handler.success
          @result = "success"
        end
      end
      
      respond_to do |format|
        # format.html { render "spree/checkout/coupon_form" }
        format.js { render "spree/checkout/coupon_form" }
      end
      
    end
  
  end
  
end

app/helpers/base_helper_decorator.rb
Spree::BaseHelper.module_eval do
  
  def flash_messages(opts = {})
    ignore_types = ["order_completed"].concat(Array(opts[:ignore_types]).map(&:to_s) || [])

    flash.each do |msg_type, text|
      unless ignore_types.include?(msg_type)
        if msg_type == "error"
          concat(content_tag :div, text, class: "alert alert-danger")
        elsif msg_type == "notice"
          concat(content_tag :div, text, class: "alert alert-info")
        end
        
      end
    end
    nil
  end
  
  def breadcrumbs(taxon, separator="")
    return "" if current_page?("/") || taxon.nil?
    
    crumbs = [[Spree.t(:home), spree.root_path]]
    
    if taxon
      crumbs << [Spree.t(:products), products_path]
      crumbs += taxon.ancestors.collect { |a| [a.name, spree.nested_taxons_path(a.permalink)] } unless taxon.ancestors.empty?
      crumbs << [taxon.name, spree.nested_taxons_path(taxon.permalink)]
    else
      crumbs << [Spree.t(:products), products_path]
    end

    separator = raw(separator)

    crumbs.map! do |crumb|
      content_tag(:li, itemscope:"itemscope", itemtype:"http://data-vocabulary.org/Breadcrumb") do
        link_to(crumb.last, itemprop: "url") do
          content_tag(:span, crumb.first, itemprop: "title")
        end + (crumb == crumbs.last ? '' : separator)
      end
    end

    content_tag(:div, content_tag(:div, raw(crumbs.map(&:mb_chars).join), class: 'breadcrumb'), id: 'breadcrumbs', class: 'hidden-xs col-sm-12 col-md-12')
  end
  
  def taxons_tree(root_taxon, current_taxon, max_level = 1)
    puts "#{root_taxon.inspect}"
    return '' if max_level < 1 || root_taxon.children.empty?
    content_tag :ul, class: 'list-group' do
      root_taxon.children.map do |taxon|
        # css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
        content_tag :li, class: "list-group-item" do
         link_to(taxon.name, seo_url(taxon)) +
         taxons_tree(taxon, current_taxon, max_level - 1)
        end
      end.join("\n").html_safe
    end
  end
  
end

app/helpers/frontend_helper_decorator.rb
Spree::FrontendHelper.module_eval do

  def checkout_progress
    states = @order.checkout_steps
    items = states.map do |state|
      text = Spree.t("order_state.#{state}").titleize

      css_classes = []
      current_index = states.index(@order.state)
      state_index = states.index(state)

      if state_index < current_index
        css_classes << 'completed'
        text = link_to text, checkout_state_path(state)
      end

      css_classes << 'next' if state_index == current_index + 1
      css_classes << 'active' if state == @order.state
      css_classes << 'first' if state_index == 0
      css_classes << 'last' if state_index == states.length - 1
      # It'd be nice to have separate classes but combining them with a dash helps out for IE6 which only sees the last class
      content_tag('li', content_tag('span', text), class: css_classes.join(' '))
    end
    content_tag('ol', raw(items.join("\n")), class: 'progress-steps breadcrumb', id: "checkout-step-#{@order.state}")
  end

end

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>
<div class="inner" data-hook=<%="#{address_type}_inner" %>>
	
	<div class="col-md-6">
		<div class="form-group col-md-6" id=<%="#{address_id}firstname" %>>
		<%= form.label :firstname, Spree.t(:first_name) %><span class="required">*</span><br />
		<%= form.text_field :firstname, :class => 'required form-control' %>
		</div>
		<div class="form-group col-md-6" id=<%="#{address_id}lastname" %>>
		<%= form.label :lastname, Spree.t(:last_name) %><span class="required">*</span><br />
		<%= form.text_field :lastname, :class => 'required form-control' %>
		</div>
		<% if Spree::Config[:company] %>
		<div class="form-group" id=<%="#{address_id}company" %>>
		<%= form.label :company, Spree.t(:company) %><br />
		<%= form.text_field :company, :class => 'form-control' %>
		</div>
		<% end %>
		<div class="form-group" id=<%="#{address_id}phone" %>>
		<%= form.label :phone, Spree.t(:phone) %><% if address.require_phone? %><span class="required">*</span><br /><% end %>
		<%= form.phone_field :phone, :class => "#{'required' if address.require_phone?} form-control" %>
		</div>
		<% if Spree::Config[:alternative_shipping_phone] %>
		<div class="field" id=<%="#{address_id}altphone" %>>
		<%= form.label :alternative_phone, Spree.t(:alternative_phone) %><br />
		<%= form.phone_field :alternative_phone %>
		</div>
		<% end %>
	</div>
	
	<div class="col-md-6">
		<div class="form-group" id=<%="#{address_id}address1" %>>
		<%= form.label :address1, Spree.t(:street_address) %><span class="required">*</span><br />
		<%= form.text_field :address1, :class => 'required form-control' %>
		</div>
		<div class="form-group" id=<%="#{address_id}address2" %>>
		<%= form.label :address2, Spree.t(:street_address_2) %><br />
		<%= form.text_field :address2, :class => 'form-control' %>
		</div>
		<div class="form-group col-md-6" id=<%="#{address_id}city" %>>
		<%= form.label :city, Spree.t(:city) %><span class="required">*</span><br />
		<%= form.text_field :city, :class => 'required form-control' %>
		</div>
		<%= form.hidden_field :country_id, :value => Spree::Country.where(:iso => "US").first.id %>
		<% address.country = Spree::Country.where(:iso => "US").first %>
		
		<div class="form-group col-md-3" id=<%="#{address_id}state" %>>
		<% have_states = !address.country.states.empty? %>
		<%= form.label :state, Spree.t(:state) %><span class='required' id=<%="#{address_id}state-required"%>>*</span><br/>
		
		<% state_elements = [form.collection_select(:state_id, address.country.states,
			:id, :name, {:include_blank => true}, {:class => have_states ? 'form-control required' : 'form-control hidden', :disabled => !have_states}) + form.text_field(:state_name, :class => !have_states ? 'form-control required' : 'form-control hidden', :disabled => have_states) ].join.gsub('"', "'").gsub("\n", "")%>
		<%= javascript_tag do -%>
			$('#<%="#{address_id}state" %>').append("<%== state_elements %>");
		<% end %>
		</div>
		<noscript>
		<%= form.text_field :state_name, :class => 'required form-control' %>
		</noscript>	
		<div class="form-group col-md-3" id=<%="#{address_id}zipcode" %>>
		<%= form.label :zipcode, Spree.t(:zip) %><% if address.require_zipcode? %><span class="required">*</span><br /><% end %>
			<%= form.text_field :zipcode, :class => "#{'required' if address.require_zipcode?} form-control" %>
		</div>
	</div>
</div>

app/views/spree/checkout/_address.html.erb
<div class="row">
	
	<div class="col-sm-6 address_wrapper" data-hook="billing_fieldset_wrapper">
		
		<div class="panel panel-default no-margin-left no-margin-right" id="billing" data-hook>
		
			<%= form.fields_for :bill_address do |bill_form| %>
		
			<div class="panel-heading">
				<h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
			</div>
		
			<div class="panel-body">
			
				<%= render :partial => 'spree/address/form', :locals => { :form => bill_form, :address_type => 'billing', :address => @order.bill_address } %>
			
				<p class="field" style='clear: both'>
					<%= form.label :email %><br />
					<%= form.text_field :email, :class => "form-control" %>
				</p>
			
			</div>
			
			<% end %>
			
		</div>
	
	</div>
	
	<div class="col-sm-6 address_wrapper" data-hook="shipping_fieldset_wrapper">
		
		<div class="panel panel-default no-margin-left no-margin-right" id="shipping" data-hook>
		
			<%= form.fields_for :ship_address do |ship_form| %>
				
			<div class="panel-heading">
				<h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
			</div>
			
			<div class="panel-body">
				
				<%= render :partial => 'spree/address/form', :locals => { :form => ship_form, :address_type => 'shipping', :address => @order.ship_address } %>
				
				<span class="field checkbox" data-hook="use_billing">
				<%= label_tag :order_use_billing, :id => 'use_billing' do %>
					<%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
					<%= Spree.t(:use_billing_address) %>
				<% end %>
				</span>
				
			</div>	
			<% end %>
			
		</div>
		
	</div>
	
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="row">
	
	<div class="col-md-12 payment_wrapper">
		<h1>PO NUMBER: <%= @order.po_number %></h1>
		<%= render :partial => 'spree/shared/order_details', :locals => { :order => @order } %>
		
	</div>

</div>

app/views/spree/checkout/_coupon_form.html.erb
<%= form_for @order, :url => apply_coupons_path(), :html => {:id => 'update-cart'}, :remote => true do |of| %>

	<h4 class="modal-title">Enter Coupon Code</h4>
	<%= of.hidden_field :order_id, :value => @order.id %>
	
	<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
	
	<div class="row">
		<div class="col-md-6">
			<%= of.text_field :coupon_code, :class => "form-control coupon_code", :placeholder => Spree.t(:coupon_code) %>
		</div>
		<div class="col-md-6">
			<%= of.submit "Apply Coupon", :type => "submit", :class => "btn btn-success" %>
		</div>
	</div>
	
<% end %>

app/views/spree/checkout/_delivery.html.erb
<div class="col-md-12 delivery_wrapper">
	
	<div id='shipping_method' data-hook>
		
		<div class="panel-body" data-hook="shipping_method_inner">
			
			<div id="methods">
			
			<%= form.fields_for :shipments do |ship_form| %>
				
				<div class="shipment">
					<table class="table table-condensed table-hover" data-hook="stock-contents">
						
						<colgroup>
							<col style="width: 15%;" />
							<col style="width: 60%;" />
							<col style="width: 3%;" />
							<col style="width: 12%;" />
							<col style="width: 12%;" />
						</colgroup>
						
						<thead>
							<tr>
								<th align='left'><%= Spree.t(:SKU) %></th>
								<th align='left'><%= Spree.t(:item) %></th>
								<th class="text-center"><%= Spree.t(:qty) %></th>
								<th class="text-right"><%= Spree.t(:price) %></th>
								<th class="text-right"><%= Spree.t(:ext_price) %></th>
							</tr>
						</thead>
						
						<tbody>
							<% ship_form.object.manifest.each do |item| %>
							<tr class="stock-item">
								<td class="item-sku"><%= item.variant.sku %>
									<div id="<%= item.variant.id %>" class="image">
										<%= mini_image(item.variant) %>
									</div>
								</td>
								<td class="item-name"><%= item.variant.name %>
									<br/><small><%= truncate(item.variant.description, :length => 40, :escape => false) %></small>
								</td>
								<td class="item-qty text-center"><%= item.quantity %></td>
								<td class="item-price text-right"><%= display_price(item.variant) %></td>
								<td class="item-price text-right"><%= number_to_currency(item.quantity * item.variant.price) %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
					
					<div class="col-md-6">
						<h4 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h4>
						
						<% ship_form.object.shipping_rates.each do |rate| %>
							<label>
								<%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
								<span class="rate-name"><%= rate.name %></span>&nbsp;<span class="badge rate-cost"><%= rate.display_cost %></span>
							</label>
							<br/>
						<% end %>
					</div>
					
					
				</div>
				
			<% end %>
			
			<% if @differentiator.try(:missing?) %>
				
				<div class="shipment unshippable">
		
					<h3 class="stock-location" data-hook="stock-location"><%= Spree.t(:unshippable_items) %></h3>
				
					<table class="table stock-contents" data-hook="stock-missing">
						<colgroup>
							<col style="width: 10%;" />
							<col style="width: 60%;" />
							<col style="width: 10%;" />
							<col style="width: 20%;" />
						</colgroup>
					
						<thead>
							<th></th>
							<th align='left'><%= Spree.t(:item) %></th>
							<th><%= Spree.t(:qty) %></th>
							<th><%= Spree.t(:price) %></th>
						</thead>
					
						<tbody>
							<% @differentiator.missing.each do |variant, quantity| %>
							<tr class="stock-item">
								<td class="item-image"><%= mini_image(variant) %></td>
								<td class="item-name"><%= variant.name %></td>
								<td class="item-qty"><%= quantity %></td>
								<td class="item-price"><%= display_price(variant) %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				
				</div>
				
			<% end %>
			
			</div>
			
			<div class="col-md-6">
				<% if Spree::Config[:shipping_instructions] %>
				<div id="minstrs" data-hook>
					<h4><%= Spree.t(:shipping_instructions) %></h4>
					<%= form.text_area :special_instructions, :cols => 40, :rows => 3, :class => "form-control" %>
				</div>
				<% end %>
			</div>
			
		</div>
			
	</div>
	
</div>

app/views/spree/checkout/_form_wrapper.html.erb
<% if !@order.user and state == "address" %>
<div class="panel panel-default" id="checkout_registration_panel">
	
	<div class="panel-heading">
		<h4 class="panel-title">Already Have an Account? <small>
			<button type="button" class="btn btn-link login-link" data-toggle="modal" data-target="#loginModal"><strong>Login</strong></button>
			for express checkout</small>
		</h4>
	</div>
	
	<%# if state == @order.state %>
	
	<%# end %>
	
</div>
<br/>
<% end %>

<% if @order.state != "confirm" %>
	<% if state != "confirm" %>
	<div class="panel panel-default" id="checkout_<%= state %>_panel">
	
		<div class="panel-heading">
			<h4 class="panel-title"><%= state.capitalize %></h4>
		</div>
	
		<% if state == @order.state %>
	
		<div class="panel-body panel-collapse collapse in <%# 'in' unless state != @order.state %>" id="checkout_<%= state %>_panel_body">
		
			<% content_for :errors do %>
				<%= render :partial => 'spree/shared/error_messages', :locals => { :target => order } %>
			<% end %>
		
			<%= form_for order, :url => update_checkout_path(state), :remote => (state != "payment"), :html => { :id => "checkout_form_#{state}" } do |x| %>
				<%= render "spree/checkout/remote/#{state}", :form => x %>
			<% end %>
		</div>
	
		<% end %>
	
	</div>
	<% end %>
<% else %>
	<% if state == "confirm" %>
	<div class="panel panel-default" id="checkout_<%= state %>_panel">
	
		<div class="panel-heading">
			<h4 class="panel-title"><%= state.capitalize %></h4>
		</div>
	
		<% if state == @order.state %>
	
		<div class="panel-body panel-collapse collapse in <%# 'in' unless state != @order.state %>" id="checkout_<%= state %>_panel_body">
		
			<% content_for :errors do %>
				<%= render :partial => 'spree/shared/error_messages', :locals => { :target => order } %>
			<% end %>
		
			<%= form_for order, :url => update_checkout_path(state), :remote => (state != "confirm"), :html => { :id => "checkout_form_#{state}" } do |x| %>
				<%= render "spree/checkout/remote/#{state}", :form => x %>
			<% end %>
		</div>
	
		<% end %>
	
	</div>
	<% end %>
<% end %>

app/views/spree/checkout/_payment.html.erb
<style>
	
	.tabs-below > .nav-tabs,
	.tabs-right > .nav-tabs,
	.tabs-left > .nav-tabs {
	  border-bottom: 0;
	}

	.tab-content > .tab-pane,
	.pill-content > .pill-pane {
	  display: none;
	}

	.tab-content > .active,
	.pill-content > .active {
	  display: table;
	}

	.tabs-below > .nav-tabs {
	  border-top: 1px solid #ddd;
	}

	.tabs-below > .nav-tabs > li {
	  margin-top: -1px;
	  margin-bottom: 0;
	}

	.tabs-below > .nav-tabs > li > a {
	  -webkit-border-radius: 0 0 4px 4px;
	     -moz-border-radius: 0 0 4px 4px;
	          border-radius: 0 0 4px 4px;
	}

	.tabs-below > .nav-tabs > li > a:hover,
	.tabs-below > .nav-tabs > li > a:focus {
	  border-top-color: #ddd;
	  border-bottom-color: transparent;
	}

	.tabs-below > .nav-tabs > .active > a,
	.tabs-below > .nav-tabs > .active > a:hover,
	.tabs-below > .nav-tabs > .active > a:focus {
	  border-color: transparent #ddd #ddd #ddd;
	}

	.tabs-left > .nav-tabs > li,
	.tabs-right > .nav-tabs > li {
	  float: none;
	}

	.tabs-left > .nav-tabs > li > a,
	.tabs-right > .nav-tabs > li > a {
	  min-width: 74px;
	  margin-right: 0;
	  margin-bottom: 3px;
	}

	.tabs-left > .nav-tabs {
	  float: left;
	  margin-right: 19px;
	  border-right: 1px solid #ddd;
	}

	.tabs-left > .nav-tabs > li > a {
	  margin-right: -1px;
	  -webkit-border-radius: 4px 0 0 4px;
	     -moz-border-radius: 4px 0 0 4px;
	          border-radius: 4px 0 0 4px;
	}

	.tabs-left > .nav-tabs > li > a:hover,
	.tabs-left > .nav-tabs > li > a:focus {
	  border-color: #eeeeee #dddddd #eeeeee #eeeeee;
	}

	.tabs-left > .nav-tabs .active > a,
	.tabs-left > .nav-tabs .active > a:hover,
	.tabs-left > .nav-tabs .active > a:focus {
	  border-color: #ddd transparent #ddd #ddd;
	  *border-right-color: #ffffff;
	}

	.tabs-right > .nav-tabs {
	  float: right;
	  margin-left: 19px;
	  border-left: 1px solid #ddd;
	}

	.tabs-right > .nav-tabs > li > a {
	  margin-left: -1px;
	  -webkit-border-radius: 0 4px 4px 0;
	     -moz-border-radius: 0 4px 4px 0;
	          border-radius: 0 4px 4px 0;
	}

	.tabs-right > .nav-tabs > li > a:hover,
	.tabs-right > .nav-tabs > li > a:focus {
	  border-color: #eeeeee #eeeeee #eeeeee #dddddd;
	}

	.tabs-right > .nav-tabs .active > a,
	.tabs-right > .nav-tabs .active > a:hover,
	.tabs-right > .nav-tabs .active > a:focus {
	  border-color: #ddd #ddd #ddd transparent;
	  *border-left-color: #ffffff;
	}
	
	.tab-content {
		display: table;
	}
	
	ul.nav.tabs {
		width: 20%;
	}
	.tab-content {
		width: 80%;
	}
	.tab-pane {
		width: 100%;
	}
</style>

<div class="col-md-12" id="payment">

	<%= yield :errors %>
	
	<div class="tabbable tabs-left">
		
		<ul class="nav nav-tabs">
			<% @order.available_payment_methods.each_with_index do |method, i| %>
			<%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
			<script>
				$("input[type=radio]#order_payments_attributes__payment_method_id_<%= method.id %>").hide()
				$("a[href=#<%= method.id %>]").click(function(e){
					$("input[type=radio]#order_payments_attributes__payment_method_id_<%= method.id %>").prop('checked', true)
					// $("input[type=radio]#order_payments_attributes__payment_method_id_<%= method.id %>").show()
				})
			</script>
			<script>
			$.getScript('/assets/spree/frontend/checkout/payment.js', function() {});
			</script>
			<li <%= i == 0 ? "class=active" : "" %>><a href="#<%= method.id %>" data-toggle="tab"><%= method.name %></a></li>
			<% end %>
		</ul>
		<div class="tab-content">
			<% @order.available_payment_methods.each_with_index do |method, i| %>
			<div class="tab-pane <%= i == 0 ? "active" : "" %>" id="<%= method.id %>"><%= render :partial => "spree/checkout/payment/#{method.method_type}", :locals => { :payment_method => method } %></div>
			<% end %>
			
			<!-- Button trigger modal -->
			<p class="text-right">
				<button type="button" class="btn btn-link coupon-link" data-toggle="modal" data-target="#myModal">
				  Have a Coupon Code?
				</button>
			</p>
		</div>
		
	</div>
</div>
<script>Spree.disableSaveOnClick();</script>

app/views/spree/checkout/_summary.html.erb
<div id="checkout_summary" class="well well-sm text-center">
	
	<h3 class="text-center cart-summary">Cart Summary</h3>
	
	Order #<%= @order.number %>
	
	<table class="table">
		
		<tr class="cart-subtotal">
			<td class="text-left"><%= Spree.t(:cart_subtotal, :count => @order.line_items.sum(:quantity)) %></td>
			<td class="text-right"><%= @order.display_item_total %></td>
		</tr>
		
		<%= render "spree/orders/adjustments" %>
	
		<tr class="cart-total">
			<td class="text-left"><h4><%= Spree.t(:total) %></h4></td>
			<td class="text-right"><h4><%= @order.display_total %></h4></td>
		</tr>
		
	</table>
	
	<% if @order.state == "address" %>
	
		<%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
		<%= label_tag :save_user_address, Spree.t(:save_my_address) %>
	
		<%= button_tag :class => 'checkout btn btn-success btn-lg btn-block', :id => 'checkout-link', :name => 'checkout', :form => "checkout_form_#{@order.state}" do %>
Proceed To Delivery!
		<% end %>
		
	<% elsif @order.state == "delivery" %>
	
		<%= button_tag :class => 'checkout btn btn-success btn-lg btn-block', :id => 'checkout-link', :name => 'checkout', :form => "checkout_form_#{@order.state}" do %>
Proceed To Payment!
		<% end %>
		
	<% elsif @order.state == "payment" %>
			
		<%= button_tag :class => 'checkout btn btn-success btn-lg btn-block', :id => 'checkout-link', :name => 'checkout', :form => "checkout_form_#{@order.state}" do %>
	Proceed To Confirm!
		<% end %>
		<script>Spree.disableSaveOnClick();</script>
	<% elsif @order.state == "confirm" %>
	
		<%= button_tag :class => 'checkout btn btn-success btn-lg btn-block', :id => 'checkout-link', :name => 'checkout', :form => "checkout_form_#{@order.state}" do %>
	Place Order!
		<% end %>
		
	<% end %>	
	
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			
			<div id="myModalBody" class="modal-body" data-hook='coupon_code'>
				
				<%= render :partial => "spree/checkout/coupon_form" %>
			</div>
			
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/spree/checkout/edit.html.erb
<h2 class="page-header">Secure Checkout&nbsp;<br/><small class="gold"><span class="glyphicon glyphicon-lock gold"></span> This is a secure 128-bit SSL encrypted page.</small></h2>


<div class="panel-group col-md-12" id="checkout" data-hook>
	
	<% @order.checkout_steps[0...4].each do |state| %>
	
		<%= render :partial => "form_wrapper", :locals => {:order => @order, :state => state} %>
	
	<% end %>
	
</div>

<div class="col-md-3" style="display:none">
	<%= render :partial => "summary", :locals => {:order => @order, :state => @order.state}%>
</div>

<script>
Spree.current_order_id = "<%= @order.number %>"
Spree.current_order_token = "<%= @order.guest_token %>"
</script>

<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			
			<div id="myModalBody" class="modal-body" data-hook='coupon_code'>
				<%= render :partial => "spree/checkout/remote/login" %>
			</div>
			
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/spree/checkout/remote/_delivery.html.erb
<div id="checkout_delivery" class="panel-collapse" role="tabpanel">
	
	<div class="panel-body">
		
		<%= render :partial => "delivery", :locals => {:order => @order, :form => form} %>
	
		<div class="col-md-12">
			<%= form.submit "Save & Continue", :class => 'btn btn-success pull-right' %>
		</div>
	
	</div>
	
</div>

app/views/spree/products/_email_to_friend.html.erb
<p class="email_to_friend"><%= link_to Spree.t('email_to_friend.send_to_friend'), email_to_friend_path('product', @product) %></p>